### ISSUE TITLE
W1/EX2: Screenreader?

### ISSUE THREAD

**Issue by KoopReynders** [TimoVerkroost/minor-browser-technologies#2]

**Comment by TimoVerkroost** [comment]
https://github.com/TimoVerkroost/minor-browser-technologies/tree/master/1.2-assignment-fork-je-funda#mousetrackpad-wont-work

Heb getest, kon er redelijk doorheen komen maar de reader roept echt van alles, zoals het type element enzo waardoor het heel raar klinkt.
